# Generated by Django 4.2.7 on 2023-11-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="user_role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_role",
        ),
        migrations.DeleteModel(
            name="Allocation",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="TimeCycle",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
