# Generated by Django 4.2.7 on 2023-12-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0004_employee_timecycle_allocation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SuperAdmin",
        ),
    ]
