# Generated by Django 4.2.7 on 2023-12-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0005_delete_superadmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("superadmin_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
    ]
