# Generated by Django 4.2.7 on 2023-12-06 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0006_superadmin"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Allocation",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="TimeCycle",
        ),
    ]
