# Generated by Django 4.2.7 on 2023-12-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0008_employee_timecycle_allocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_role",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
