# Generated by Django 4.2.7 on 2023-12-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0010_user_permission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
