# Generated by Django 4.2.7 on 2023-12-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0015_delete_token_user_last_login_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
