# Generated by Django 4.2.7 on 2023-12-07 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0016_remove_user_last_login_alter_user_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
