# Generated by Django 4.2.7 on 2023-12-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0020_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
