# Generated by Django 4.2.7 on 2023-12-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0025_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="user_role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_role",
        ),
        migrations.DeleteModel(
            name="AccessToken",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
