# Generated by Django 4.2.7 on 2023-12-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0027_userrole_user_accesstoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
