# Generated by Django 4.2.7 on 2023-12-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0029_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role_name",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="AccessToken",
        ),
    ]
