# Generated by Django 4.2.7 on 2023-12-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0030_alter_userrole_role_name_delete_accesstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role_name",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permission_name", models.CharField(max_length=50)),
                ("allowed", models.BooleanField(default=False)),
                (
                    "user_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App1.userrole"
                    ),
                ),
            ],
        ),
    ]
