# Generated by Django 4.2.7 on 2023-12-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0034_usertoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserToken",
        ),
    ]
