# Generated by Django 4.2.7 on 2023-12-07 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0036_accesstoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_role",
        ),
        migrations.DeleteModel(
            name="AccessToken",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
