# Generated by Django 4.2.7 on 2023-12-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0046_passwordresettoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
