# Generated by Django 4.2.7 on 2023-12-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0051_timecycleday"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TimeCycleDay",
        ),
    ]
