# Generated by Django 4.2.7 on 2023-12-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0053_timecycleday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timecycleday",
            name="time_cycle",
        ),
        migrations.DeleteModel(
            name="Allocation",
        ),
        migrations.DeleteModel(
            name="TimeCycle",
        ),
        migrations.DeleteModel(
            name="TimeCycleDay",
        ),
    ]
