# Generated by Django 4.2.7 on 2023-12-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0056_rename_token_passwordresettoken_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresettoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="App1.customuser"
            ),
        ),
    ]
