# Generated by Django 4.2.7 on 2023-12-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0057_alter_passwordresettoken_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
