# Generated by Django 4.2.7 on 2023-12-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0061_alter_passwordresettoken_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=10,
            ),
        ),
    ]
