# Generated by Django 4.2.7 on 2023-12-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0062_customuser_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedUserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archived_role_name", models.CharField(max_length=100)),
            ],
        ),
    ]
