# Generated by Django 4.2.7 on 2023-12-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0065_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accesstoken",
            name="user",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="allocation",
            name="time_cycle",
        ),
        migrations.DeleteModel(
            name="ArchivedUserRole",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_role",
        ),
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="user",
        ),
        migrations.RemoveField(
            model_name="permission",
            name="user_role",
        ),
        migrations.DeleteModel(
            name="SuperAdmin",
        ),
        migrations.RemoveField(
            model_name="timecycleday",
            name="time_cycle",
        ),
        migrations.DeleteModel(
            name="AccessToken",
        ),
        migrations.DeleteModel(
            name="Allocation",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="TimeCycle",
        ),
        migrations.DeleteModel(
            name="TimeCycleDay",
        ),
        migrations.DeleteModel(
            name="UserRole",
        ),
    ]
